### ISSUE TITLE
Unable to build SoundTools

### ISSUE THREAD

**Issue by ergodaveh** [AddictedCS/soundfingerprinting.soundtools#2]
Just cloned the project today to discover

Unable to find version '3.0.0-beta2' of package 'SoundFingerprinting.NeuralHasher'.	SoundFingerprinting.SoundTools

**Comment by AddictedCS** [comment]
Will push neural hasher to nuget next week.

**Comment by ergodaveh** [comment]
Looking forward to that time.   Thanks

**Comment by AddictedCS** [comment]
Fixed.
